version: 0.0
os: linux

files:
  - source: /Frontend
    destination: /home/ubuntu/deploy-fe
    overwrite: yes
  - source: /Backend
    destination: /home/ubuntu/deploy-be
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/deploy-fe
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /home/ubuntu/deploy-be
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: root
